### ISSUE TITLE
pdf2text

### ISSUE THREAD

**Issue by boolbag** [Code4SA/gazettes-liquor-extractor#4]
@adieyal 
It would be helpful to have a text file or script detailing the steps for the alternate method you mentioned to me. Do you have it as a Jupyter notebook, script, sequence of commands...?

You said that the method uses _pdf2text_. Since there are [many things called *pdf2text*](https://www.google.com/search?output=search&sclient=psy-ab&q=pdf2text&btnG=&oq=&gs_l=&pbx=1), an explanation would be super helpful.

For reference, here is a fragment of the output you shared with me:
```('Name:', '')
('Applicant Details:', 'NAMISHI ERIC MAREBANE, (6406185445080),\nSTAND NO:2,MABOCHA VILLAGE,ROOIBOKLAAGTE\nFARM NO:259KT, BOX 1192 BURGERSFORT 1150.')
('License Category:', 'SPECIAL LICENCE-LIQUOR TAVERN.')
('Liquor Type:', 'ALL KINDS.')
('Business Details:', 'BAKONI\nTAVERN,\nSTAND\nNO:2,MABOCHA\nVILLAGE,ROOIBOKLAAGTE FARM NO:259KT.')
('Authority:', 'AUTHORITY IN TERMS OF SECTION 41(1)(a).')
```

Thanks in advance!

**Comment by adieyal** [comment]
This is the tool: https://www.cyberciti.biz/faq/converter-pdf-files-to-text-format-command/

I ran it with pdftotext <filename>

it has another option pdftotext -layout <filename> which produces a much nicer output. It doesn't work with your regular expressions but I suspect that you would get a much higher quality extraction using that instead.

**Comment by boolbag** [comment]
Thank you for sharing the link of the tool. Tried pdftotext on CentOS. Very fast. 

And I realize that I probably had misunderstood you. 
I had thought that the output above was generated **just** by running pdftotext. That seemed like a lot of magic and I was blown away.

What I'm now getting is that it was generated by **chaining** pdftotext and the regex script. Is that right?

So with that solution, on a machine where pdftotext can run, something like that could be added:
```os.system(' '.join(['pdftotext', pdf_file_path, ouput_txt__file_path]))```

Or, as you said, use the *layout* option and tweak the regex.

Specifying a widely-available conversion tool has the advantage of producing results which are easier to reproduce than with Acro11. 

Is pdftotext something you're using regularly because you frequently survey the field? Nice that it's a zero-scaffolding solution, as opposed to what you have to do with Python modules such as [pdfminer](https://github.com/goulu/pdfminer). For my part I haven't compared available tools. 

[This review](http://okfnlabs.org/blog/2016/04/19/pdf-tools-extract-text-and-data-from-pdfs.html) looks promising. 

Coming full circle, it points to [an article](http://okfnlabs.org/blog/2013/12/25/parsing-pdfs.html) that suggests a similar approach:

> My approach is pretty crude. For the PDFs that aren’t scans, I just use pdftotext.
> Then I just use regular expressions to search the resulting text file.

Of course Python is not the only language suitable for data extraction pipelines. And when you need to distribute extractions, there are even standalone tools that let you set up jobs which are lists of actions, such as those performed with the regular expressions in the script. Non-developer clients can then purchase the tool and run the job files. But that's way off-topic. Time to end this novel. :)

**Comment by adieyal** [comment]
Yep, pdftotext + regex

-layout is my default option. It generally does a very good job of preserving the layout of the pdf which is often good enough. Interestingly enough pdfminer comes with pdf2txt.py -html which retains much of the styling of the text placing it in inline styles. That's useful if you need to be able to extract text which may have been highlighted or printed in a different font.

I tested it on the liquour gazettes but the DOM that it produced differed enough between years that it wasn't worth parsing.

**Comment by boolbag** [comment]
Thank you for sharing what you've found. Interested to see how these conversion tools go over time. Since we've explored the topic in the title, closing it -- but feel free to reopen.
